---
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
install:
  - pip install pyyaml flake8 coveralls
  - pip install .
script:
  - flake8 .
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - coverage run --source=yamllint setup.py test
after_success:
  coveralls
