---

rules:
  # block-sequence-indentation:
  #   present: yes
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  comments:
    level: warning
    require-starting-space: yes
    min-spaces-from-content: 2
  document-end: disable
  document-start:
    level: warning
    present: yes
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    # indent-lists: yes
    # check-comments: yes
  line-length:
    max: 80
  new-line-at-end-of-file: {level: error}
  new-lines:
    type: unix
  trailing-spaces: {}
